all:
  hosts:
    apache:
      ansible_host: 192.168.1.118
    mail:
      ansible_host: 192.168.1.214
    docker:
      ansible_host: 192.168.1.146
    pvr:
      ansible_host: 192.168.1.124
  children:
    servers:
      hosts:
        apache:
        mail:
        docker:
        pvr:
      vars:
        ansible_user: swmiller6
        ansible_sudo_pass: irontree42
    sandbox:
      hosts:
        192.168.1.170:
      vars:
        ansible_user: dom01
        ansible_sudo_pass: '!r0ntr3342' 
    pi:
      hosts:
        192.168.1.164:
      vars:
        ansible_user: dietpi
        ansible_sudo_pass: irontree42
